//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueDynamicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url_config_tabl
    {
        public int ID { get; set; }
        public string Endpoint_name { get; set; }
        public string url { get; set; }
        public string url_param { get; set; }
        public Nullable<int> interval_number { get; set; }
        public string Report_Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public System.DateTimeOffset UpdateDate { get; set; }
    }
}
