//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueDynamicWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Data
    {
        public int UserDataId { get; set; }
        public string Name { get; set; }
        public string UserEmail { get; set; }
        public string PhoneNo { get; set; }
        public string ShiftTiming { get; set; }
        public string ManagerName { get; set; }
        public string ManagerEmail { get; set; }
        public string Tower { get; set; }
        public string Password { get; set; }
    }
}
